### ISSUE TITLE
GitHub stats not showing up

### ISSUE THREAD

**Issue by KouroshKSH** [matheusfelipeog/matheusfelipeog#1]
# Fixing Statistics Issue
Greetings Matheus,

Before I start, I have to say that your GitHub profile inspired me to make my own; so thank you for that. Regarding the bug, I realized that the *GitHub Stats* section was facing some issues and would show this error message on both of our profiles:

![image](https://user-images.githubusercontent.com/65996638/229846053-9bce3c8a-6b5c-405e-bc61-29ac4181d4ce.png)

> A screenshot of what users see

---

## Suggestion
I personally went about fixing mine by visiting [Anurag's](https://github.com/anuraghazra/github-readme-stats) repo and making another "GtiHub stats card" from scratch. This is what I currently have, which updates itself regularly and shows the stats correctly:

```html
<p align="left">
  <img src="https://github-readme-stats.vercel.app/api?username=KouroshKSH&count_private=true&show_icons=true&theme=github_dark" alt="General Stats" width="475px" />
</p>
```

I guess your current code is not much different, however, rewriting it might help. This is what you currently have in your `README.md` file:

```html
<details>
    <summary>My GitHub stats</summary>
    <br />
    <p align="center">
        <img src="https://github-profile-trophy.vercel.app/?username=matheusfelipeog&theme=darkhub&margin-w=15" alt="Trophies GitHub" />
    </p>
    <p align="center">
        <img src="https://github-readme-stats.vercel.app/api?username=matheusfelipeog&theme=dark&show_icons=true&include_all_commits=true&locale=en" alt="General Statistics" />
    </p>
    <p align="center">
        <img src="https://github-readme-streak-stats.herokuapp.com/?user=matheusfelipeog&theme=dark" alt="Streak Stats" />
    </p>
    <p align="center">
        <img src="https://github-readme-stats.vercel.app/api/top-langs?username=matheusfelipeog&layout=compact&theme=dark&locale=en" alt="Techs used in projects" width="495px" />
    </p>
    <p align="center">
        <img src="https://activity-graph.herokuapp.com/graph?username=matheusfelipeog&theme=xcode&bg_color=151515" alt="Activity Graph" />
    </p>
</details>
```

---

## Conclusion
I hope this helps. Thank you once again for the inspiration. Keep up the great work!

**Comment by matheusfelipeog** [comment]
Hi @KouroshKSH,

First, sorry for the delay in responding. 😅

I am happy to know that my profile served as an inspiration to create yours. Thanks for telling me that ❤

### About the issue
Well, apparently this is an availability issue and it can probably always happen when having a large number of hits. So there's not much I can do about this specific graphs, but I found that one of the other graphs also had an issue due to this issue and fixed it in: https://github.com/matheusfelipeog/matheusfelipeog/commit/3728041d916babc8f082dc6dd1b135b086eb17d7

Thank you very much for your contribution. ;)
